### ISSUE TITLE
Jupyter Notebook password

### ISSUE THREAD

**Issue by BhavanaR** [nirmalyaghosh/deep-learning-vm#2]
When I tried to access the jupyter notebook at http://localhost:8100. It's prompting for a password. What is the password?

**Comment by nirmalyaghosh** [comment]
I am curious about the password prompt you see. No password has been set anywhere. You may refer to the `setup.sh` and `Vagrantfile`.

**Comment by nirmalyaghosh** [comment]
I have pushed a commit that fixes this (password prompt) issue with a predefined password, 'password'
